export enum ActionType {
    ADD_DIGIT = "ADD_DIGIT",
    ADD_OPERATOR = "ADD_OPERATOR",
    ADD_PUISSANCE = "ADD_PUISSANCE",
    ADD_VIRGULE = "ADD_VIRGULE",
    ADD_PARENTHESE = "ADD_PARENTHESE",
    SWITCH_MODE = "SWITCH_MODE",
    CLEAR = "CLEAR",
    EVALUATE = "EVALUATE"
}